final Map<String, String> state= {
  '01': 'Alabama',
  '02': 'Alaska',
  '04': 'Arizona',
  '05': 'Arkansas',
  '06': 'California',
  '08': 'Colorado',
  '09': 'Connecticut',
  '10': 'Delaware',
  '12': 'Florida',
  '13': 'Georgia',
  '15': 'Hawaii',
  '16': 'Idaho',
  '17': 'Illinois',
  '18': 'Indiana',
  '19': 'Iowa',
  '20': 'Kansas',
  '21': 'Kentucky',
  '22': 'Louisiana',
  '23': 'Maine',
  '24': 'Maryland',
  '25': 'Massachusetts',
  '26': 'Michigan',
  '27': 'Minnesota',
  '28': 'Mississippi',
  '29': 'Missouri',
  '30': 'Montana',
  '31': 'Nebraska',
  '32': 'Nevada',
  '33': 'New Hampshire',
  '35': 'New Jersey',
  '36': 'New Mexico',
  '37': 'New York',
  '38': 'North Carolina',
  '39': 'North Dakota',
  '40': 'Ohio	OH',
  '41': 'Oklahoma',
  '42': 'Oregon',
  '43': 'Pennsylvania',
  '44': 'Rhode Island',
  '45': 'South Carolina',
  '46': 'South Dakota',
  '47': 'Tennessee',
  '48': 'Texas	',
  '49': 'Utah',
  '50': 'Vermont',
  '51': 'Virginia',
  '52': 'Washington',
  '53': 'West Virginia',
  '54': 'Wisconsin',
  '55': 'Wyoming',
  '56': 'American Samoa',
  '60': 'Guam',
  '66': 'Northern Mariana Islands',
  '72': 'Puerto Rico',
  '78': 'Virgin Islands'
};
